# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle install --path vendor/bundle
      - run:
          name: run tests
          command: ./run-test.sh

